// GENERATED by @edgedb/generate v0.3.0
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $FitchleNodeλShape = $.typeutil.flatten<_std.$Object_a5651777108811ee82a44f13c3f73ceeλShape & {
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
}>;
type $FitchleNode = $.ObjectType<"default::FitchleNode", $FitchleNodeλShape, null, [
  ..._std.$Object_a5651777108811ee82a44f13c3f73cee['__exclusives__'],
  {name: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $FitchleNode = $.makeType<$FitchleNode>(_.spec, "a7b87742-1b31-11ee-be9e-3f5f1a3c840d", _.syntax.literal);

const FitchleNode: $.$expr_PathNode<$.TypeSet<$FitchleNode, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($FitchleNode, $.Cardinality.Many), null);



export { $FitchleNode, FitchleNode };

type __defaultExports = {
  "FitchleNode": typeof FitchleNode
};
const __defaultExports: __defaultExports = {
  "FitchleNode": FitchleNode
};
export default __defaultExports;
