version: "3.8"
services:
  edgedb:
    build:
      context: .
      dockerfile: images/Dockerfile.stackfitch
    networks:
      - database
    container_name: database
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_DBNAME}"
    ports:
      - "${PORT}:5432"

networks:
  database:
    external: true
