version: "3.8"
services:
  edgedb:
    image: edgedb/edgedb
    container_name: database
    environment:
      EDGEDB_SERVER_PASSWORD: "${DB_PASSWORD}"
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"
